-- ~/.config/hypr/hyprland.lua
-- Translated from niri/mutable.kdl

hl.config({
    autogenerated = false,

    monitor = {
        "HDMI-A-1, highres, auto, 1"
    },

    env = {
        "XDG_CURRENT_DESKTOP,Hyprland",
        "QT_QPA_PLATFORM,wayland",
        "ELECTRON_OZONE_PLATFORM_HINT,auto",
        "_JAVA_AWT_WM_NONREPARENTING,1",
    },

    input = {
        kb_layout = "us",
        numlock_by_default = true,
        touchpad = {
            tap_to_click = true,
            natural_scroll = true,
        },
        accel_profile = "flat",
    },

    general = {
        gaps_in = 8,
        gaps_out = 16,
        border_size = 4,
        ["col.active_border"] = "rgba(7fc8ffff)",
        ["col.inactive_border"] = "rgba(505050ff)",
        layout = "scrolling",
    },

    decoration = {
        rounding = 12,
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        shadow = {
            enabled = true,
            range = 5,
            render_power = 3,
            color = "rgba(00000064)",
            offset = "0, 5",
        },
    },

    animations = {
        enabled = true,
    },

    scrolling = {
        fullscreen_on_one_column = true,
        column_width = 0.5,
        focus_fit_method = 1,
    },

    windowrulev2 = {
        -- App specific sizing & behavior
        "float, class:^(firefox)$, title:^(Picture-in-Picture)$",
        "float, class:^(zen)$, title:^(Picture-in-Picture)$",
        "float, title:^(Emulator|Android Emulator)$",
        "float, class:^(org.quickshell)$",
        
        -- Opacity overrides
        "opacity 0.85 0.85, class:^(org.wezfurlong.wezterm|Alacritty|com.mitchellh.ghostty|kitty)$",
        "opacity 0.98 0.98, class:^(code)$",
        
        -- Border overrides
        "noborder, class:^(org.wezfurlong.wezterm|Alacritty|zen|com.mitchellh.ghostty|kitty|org.gnome.*)$",
    },

    layerrule = {
        -- Placeholders for DMS layer rules (dms is handled separately, but as per kdl)
    },

    bind = {
        -- App launchers
        {"SUPER", "T", "exec", "kitty"},
        {"SUPER", "Space", "exec", "dms ipc call spotlight toggle"},
        
        -- Window management
        {"SUPER", "Q", "killactive", ""},
        {"SUPER", "F", "fullscreen", "1"},
        {"SUPER SHIFT", "F", "fullscreen", "0"},
        {"SUPER", "V", "togglefloating", ""},
        {"SUPER SHIFT", "V", "togglefloating", ""},

        -- Focus
        {"SUPER", "left", "movefocus", "l"},
        {"SUPER", "right", "movefocus", "r"},
        {"SUPER", "up", "movefocus", "u"},
        {"SUPER", "down", "movefocus", "d"},
        {"SUPER", "H", "movefocus", "l"},
        {"SUPER", "L", "movefocus", "r"},
        {"SUPER", "K", "movefocus", "u"},
        {"SUPER", "J", "movefocus", "d"},

        -- Move window
        {"SUPER CTRL", "left", "movewindow", "l"},
        {"SUPER CTRL", "right", "movewindow", "r"},
        {"SUPER CTRL", "up", "movewindow", "u"},
        {"SUPER CTRL", "down", "movewindow", "d"},
        {"SUPER CTRL", "H", "movewindow", "l"},
        {"SUPER CTRL", "L", "movewindow", "r"},
        {"SUPER CTRL", "K", "movewindow", "u"},
        {"SUPER CTRL", "J", "movewindow", "d"},

        -- Workspaces
        {"SUPER", "1", "workspace", "1"},
        {"SUPER", "2", "workspace", "2"},
        {"SUPER", "3", "workspace", "3"},
        {"SUPER", "4", "workspace", "4"},
        {"SUPER", "5", "workspace", "5"},
        {"SUPER", "6", "workspace", "6"},
        {"SUPER", "7", "workspace", "7"},
        {"SUPER", "8", "workspace", "8"},
        {"SUPER", "9", "workspace", "9"},
        
        {"SUPER CTRL", "1", "movetoworkspace", "1"},
        {"SUPER CTRL", "2", "movetoworkspace", "2"},
        {"SUPER CTRL", "3", "movetoworkspace", "3"},
        {"SUPER CTRL", "4", "movetoworkspace", "4"},
        {"SUPER CTRL", "5", "movetoworkspace", "5"},
        {"SUPER CTRL", "6", "movetoworkspace", "6"},
        {"SUPER CTRL", "7", "movetoworkspace", "7"},
        {"SUPER CTRL", "8", "movetoworkspace", "8"},
        {"SUPER CTRL", "9", "movetoworkspace", "9"},

        {"SUPER", "Page_Down", "workspace", "m+1"},
        {"SUPER", "Page_Up", "workspace", "m-1"},
        {"SUPER", "U", "workspace", "m+1"},
        {"SUPER", "I", "workspace", "m-1"},

        {"SUPER SHIFT", "Page_Down", "workspace", "m+1"},
        {"SUPER SHIFT", "Page_Up", "workspace", "m-1"},

        -- Screenshots
        { "", "Print", "exec", "grim -g \"$(slurp)\" - | swappy -f -" },
        { "CTRL", "Print", "exec", "grim - | swappy -f -" },
        { "ALT", "Print", "exec", "grim -g \"$(hyprctl activewindow -j | jq -r '.at[0],.at[1],.size[0],.size[1]' | paste -sd,)\" - | swappy -f -" },

        -- System commands
        { "SUPER SHIFT", "E", "exit", "" },
        { "CTRL ALT", "Delete", "exit", "" },
        { "SUPER SHIFT CTRL", "P", "exec", "shutdown now" },
        
        -- Mouse extra buttons
        { "", "mouse:276", "exec", "bash /home/loystonpais/Shells/shotllayer/set-screenshot-slurp.sh" },
        { "", "mouse:277", "exec", "bash /home/loystonpais/Shells/shotllayer/run.sh" },
    },

    bindel = {
        { "", "XF86AudioRaiseVolume", "exec", "dms ipc call audio increment 3" },
        { "", "XF86AudioLowerVolume", "exec", "dms ipc call audio decrement 3" },
        { "", "XF86AudioMute", "exec", "dms ipc call audio mute" },
        { "SUPER SHIFT", "Space", "exec", "playerctl play-pause" },
        { "", "XF86AudioPlay", "exec", "playerctl play-pause" },
        { "", "XF86AudioStop", "exec", "playerctl stop" },
        { "", "XF86AudioPrev", "exec", "playerctl previous" },
        { "", "XF86AudioNext", "exec", "playerctl next" },
        { "", "XF86MonBrightnessUp", "exec", "brightnessctl set +10%" },
        { "", "XF86MonBrightnessDown", "exec", "brightnessctl set 10%-" },
    },

    bindm = {
        {"SUPER", "mouse:272", "movewindow"},
        {"SUPER", "mouse:273", "resizewindow"},
    }
})
