name: Cachix

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: loystonpais
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --print-out-paths