name: Nextjs Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs

      # Build the project
      - name: Build Nextjs project
        run: |
          npm install --force
          npm run build

      # Compress the files
      - name: Compress the files
        run: |
          tar -czf release.tar.gz .next public package.json

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.tar.gz