name: Deploy nixacle
 
on:
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
 
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          extra-conf: |
            experimental-features = nix-command flakes
 
      - name: Trust Tailscale SSH host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H nixacle >> ~/.ssh/known_hosts

      - name: Install nixos-rebuild
        run: |
          nix profile add nixpkgs#nixos-rebuild-ng

      - name: Deploy NixOS
        run: |
          nixos-rebuild switch \
            --flake .#nixacle \
            --use-substitutes \
            --target-host root@nixacle